---
title: "Getting and Cleaning Data Course Project"
author: "Dan S."
date: "2015-07-26"
output:
  txt_document:
    keep_md: yes
---

## Project Description
The purpose of this project is to demonstrate the ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. The project is based on the data collected from the accelerometers from the Samsung Galaxy S smartphone that represented at UCI Machine Lerning Repository as Human Activity Recognition Using Smartphones Data Set 

##Study design and data processing

###Collection of the raw data
Initial raw data was downloaded from UCI Machine Learning repository

###Notes on the original (raw) data 

##Creating the tidy datafile

###Guide to create the tidy data file
Description on how to create the tidy data file (1. download the data, ...)/

###Cleaning of the data
Short, high-level description of what the cleaning script does. [click here](https://github.com/DanSpiny/Getting-and-Cleaning-Data-Course-Project/blob/master/README.md)

##Description of the variables in the tiny_data.txt file
 - Dimensions of the dataset: 180 rows (observations) x  68 columns (variables)
 - Summary of the data
 - Variables present in the dataset

(you can easily use Rcode for this, just load the dataset and provide the information directly form the tidy data file)

###Variable 1 (repeat this section for all variables in the dataset)
Short description of what the variable describes.

Some information on the variable including:
 - Class of the variable
 - Unique values/levels of the variable
 - Unit of measurement (if no unit of measurement list this as well)
 - In case names follow some schema, describe how entries were constructed (for example time-body-gyroscope-z has 4 levels of descriptors. Describe these 4 levels). 

(you can easily use Rcode for this, just load the dataset and provide the information directly form the tidy data file)

####Notes on variable 1:
If available, some additional notes on the variable not covered elsewehere. If no notes are present leave this section out.

##Sources
Sources you used if any, otherise leave out.

##Annex
If you used any code in the codebook that had the echo=FALSE attribute post this here (make sure you set the results parameter to 'hide' as you do not want the results to show again)
